name: Open Data Scraping Actions - senado.cl
on:
  push:
    branches: [ master ]
    paths:
      - 'layers/**'
      - 'senado.cl/**'
      - '.github/workflows/senado-cl.yml'
      - '!**/README.md'

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  senado-cl:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Cache for turbo
        uses: rharkor/caching-for-turbo@v1.5

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build Layers
        run: |
          pnpm layers:build

      - name: Build SRC
        run: |
          pnpm @senado.cl/packages:build
          pnpm @senado.cl/packages:package

      - name: Build IAC
        working-directory: './senado.cl/iac'
        run: |
          npm install

      - name: CDK Deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          working_dir: './senado.cl/iac'
          cdk_stack: 'odata-scraping-senado-cl'
          cdk_args: '--require-approval never'
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
